version: "3.9"

services:
  api:
    image: myregistry.com/stats-api:latest
    container_name: stats-api
    restart: always
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - stats-net

  db:
    image: postgres:16
    container_name: stats-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stats-net

networks:
  stats-net:

volumes:
  postgres_data:
